### PR TITLE
Update antitag.py

### PR DESCRIPTION
**Pull request by penn5**

### CODE REVIEW

**Comment by Lonami** [comment]
There can only be one MURTPITOTC. If you become the MURTPITOTC, I will change the ID for yours. This patch doesn't handle the different usernames anyway.

**Comment by Lonami** [comment]
Painor's suggestion at https://github.com/Lonami/TelethonianBotExt/commit/27217bf9f3f5b2173c4cf4b276fc2b9ed8bb6a18 may be worth a PR though.

**Comment by penn5** [comment]
@lonami you misunderstood my pr, it doesn't make admins protected, it makes admins exempt from protection (so admins can tag the MURTPITOTC)

**Comment by Lonami** [comment]
You're right. If the pull request's title, commit message, or a description of the changes would've been provided, this probably wouldn't have happened.

**Pull request merged**
